cert_file = """
-----BEGIN CERTIFICATE-----
MIIDIDCCAgigAwIBAgIULUh1e4IwJA2cEdvEclr4DMyuDvQwDQYJKoZIhvcNAQEL
BQAwFzEVMBMGA1UEAwwMNjUuMjEuMTk2LjE0MB4XDTI0MDkwNTEzNTYyMloXDTI1
MDkwNTEzNTYyMlowFzEVMBMGA1UEAwwMNjUuMjEuMTk2LjE0MIIBIjANBgkqhkiG
9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5bD2kyTG9LasG2Xj6ElYf9O5twXukRaowcBg
YY3DdjZtVj/cROfHAI46E44avSg1KUDnO2hGZoQnb2smWHuueM3O11c9r9x2lkZD
aZm7uuDM1lYWSRmnECu3xDkibLK2i1IKSOvzkw2hp6OHgoumemNATqb7yBvPUYIv
Ugf3rx/MXq+NKzM240+fxc1SF8RViocw3b2fXkskuj4eHfO3cyLixXOcPqsZfHQq
c5OfRdfTcFtHOqe1mp4qfFAmXbzuuuxyfd+LPgo3e4gCaEZ1FCUGsww32P+U9dYE
/9Oiems2bNlSh29PRsODCQwQNReY08noL2sQJnO02nSUd5xYbwIDAQABo2QwYjAd
BgNVHQ4EFgQUBYrTiOBBjzqucO6tJgrGHK+RplgwHwYDVR0jBBgwFoAUBYrTiOBB
jzqucO6tJgrGHK+RplgwDwYDVR0TAQH/BAUwAwEB/zAPBgNVHREECDAGhwRBFcQO
MA0GCSqGSIb3DQEBCwUAA4IBAQBIIr5RqJvUc7tCrXFPeIp8/AVDk4cKylVVaFP6
hZRFeLtxK3tR350RMnCVwk9twbJl+1kWQXroI58f6d9I8lb0Bj1TuupadRhZkcCx
G4Eak0hSQ2yyQ634CiijOJz5d1ZVQ3maFM8qcjOtqP46by2WoUv2Kn31Rv6RP9WK
srbws+r4x6/WC1ru8qQWqmgrQxQNoCj9tw3YslYhy0hkDbdPsYcOcSmJLNsaQcGu
mF7jZoWh6l48B0PyIGEH4pjdZ0DxIle/X+a81+J9ErShruQojIwvoMbALFp5nH+m
7MFwwWUiYd/Evu8/S+SYwnqOmIqjlfSwWPcOTqXoJSVTK5F8
-----END CERTIFICATE-----
"""
token_url = "https://65.21.196.14:8090/token"
main_model_url = "https://65.21.196.14:8090/serve/catboost_cdc"
extended_model_url = "https://65.21.196.14:8090/serve/logreg_cdc"
OPEN_AI_API_KEY = "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"